spring:
  cloud:
    stream:
      bindings:
        input:
          destination: local.orders
          binder:
            rabbit
          group: orders-consumers
      binders:
        rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
          
server:
  port: 9504
